name: Test

on:
  workflow_dispatch:

jobs:
  check-sign:
    runs-on: windows-latest
    steps:
      - name: Check to add github_path
        run: |
          echo 123 >> $GITHUB_PATH
          $GITHUB_PATH
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install Windows SDK
        run: choco install windows-sdk-10.0
      - name: Cache SDK
        uses: actions/cache@v2
        with:
          path: C:\Program Files (x86)\Microsoft SDKs
          key: SDK
      - name: Check signer
        run: |
          # Работает
          # & "C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool\signtool.exe"     
          
          # Работает
          # cd "C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool"
          # ls
          # .\signtool.exe
          
          # Не уверен, что добавляет
          # $Env:Path
          # $Env:Path += ';C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool'
          # signtool
          # $Env:Path
          
          # Работает
          echo 'C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool' >> $GITHUB_PATH
          $GITHUB_PATH
      - name: Check signer next step
        run: |
          signtool
          


















