name: Test

on:
  workflow_dispatch:

jobs:
  check-sign:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        
      - name: Check to add github_path
        run: |
          # Не добавляет
          # echo 123 >> $GITHUB_PATH

          # Добавляет
          echo "Folder PATH" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo $env:GITHUB_PATH

          # Но так не выводит
          # echo $GITHUB_PATH - видимо доступ только через $env:...
          echo $env:GITHUB_WORKSPACE

      - name: Cache SDK
        id: cache-sdk
        uses: actions/cache@v2
        with:
          path: C:\Program Files (x86)\Microsoft SDKs
          key: SDK
          
      - name: Install Windows SDK
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        run: choco install windows-sdk-10.0
          
      - name: Check signer
        run: |
          # Работает
          # & "C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool\signtool.exe"     
          
          # Работает
          # cd "C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool"
          # ls
          # .\signtool.exe
          
          # Не уверен, что добавляет
          # $Env:Path
          # $Env:Path += ';C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool'
          # signtool
          # $Env:Path
          
          # Не работает
          # echo 'C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool' >> $GITHUB_PATH
          # $GITHUB_PATH

          # Проверка
          echo 'C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool' | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo $env
          echo '-----------------------------'
          echo $env:GITHUB_PATH
          signtool
          
          
      - name: Check signer next step
        run: |
          # Не  работает
          # signtool
          


















